default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bookstore_development_database
  host: localhost
  port: 5432
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>


test:
  <<: *default
  database: bookstore_test_database
  host: localhost
  port: 5432
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>