default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: bookstore_development_database
  host: localhost
  port: 5432
  username: postgres
  password: 9119


test:
  <<: *default
  database:  bookstore_test_database
  username: postgres
  password: 9119
  host: localhost
  port: 5432


# production:
  # primary: &primary_production
  #   <<: *default
  #   database: backend_production
  #   username: backend
  #   password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
  # cache:
  #   <<: *primary_production
  #   database: backend_production_cache
  #   migrations_paths: db/cache_migrate
  # queue:
  #   <<: *primary_production
  #   database: backend_production_queue
  #   migrations_paths: db/queue_migrate
  # cable:
  #   <<: *primary_production
  #   database: backend_production_cable
  #   migrations_paths: db/cable_migrate
