default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: bookstore_development_database
  host: localhost
  port: 5432
  username: postgres
  password: Varun0709


test:
  <<: *default
  database:  bookstore_test_database
  username: postgres
  password: Varun0709
  host: localhost
  port: 5432
